# Docker Compose
services:
  frontend:
    build:
      context: './frontend'
    environment:
    - BLANK_ENV_VAR=nothing
    ports:
    - "3000:3000"
  backend:
    build:
      context: './backend'
    environment:
      - BLANK_ENV_VAR=nothing
  nginx:
    build:
      context: './nginx'
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - frontend
    - backend
    volumes:
    - type: bind
      source: /etc/ssl/
      target: /etc/ssl/